// Demo data for when API is not available
export const demoData = {
  beneficiaries: [
    {
      id: 1,
      name: 'Rajesh Kumar',
      age: 28,
      gender: 'Male',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      caste_category: 'SC',
      aadhar_number: '123456789012',
      phone: '9876543210',
      email: 'rajesh.kumar@email.com',
      education_level: 'Secondary',
      annual_income: 45000,
      family_size: 6,
      occupation: 'Farmer',
      skills: 'Agriculture, Animal Husbandry',
      bank_account: '1234567890123456',
      ifsc_code: 'SBIN0000001',
      eligibility_score: 85,
      is_verified: 1,
      created_at: '2024-01-15T10:30:00Z'
    },
    {
      id: 2,
      name: 'Priya Sharma',
      age: 24,
      gender: 'Female',
      state: 'Bihar',
      district: 'Patna',
      caste_category: 'SC',
      aadhar_number: '234567890123',
      phone: '9876543211',
      email: 'priya.sharma@email.com',
      education_level: 'Higher Secondary',
      annual_income: 35000,
      family_size: 5,
      occupation: 'Tailor',
      skills: 'Tailoring, Embroidery',
      bank_account: '2345678901234567',
      ifsc_code: 'SBIN0000002',
      eligibility_score: 90,
      is_verified: 1,
      created_at: '2024-01-16T11:15:00Z'
    },
    {
      id: 3,
      name: 'Amit Singh',
      age: 32,
      gender: 'Male',
      state: 'Madhya Pradesh',
      district: 'Bhopal',
      caste_category: 'SC',
      aadhar_number: '345678901234',
      phone: '9876543212',
      email: 'amit.singh@email.com',
      education_level: 'Primary',
      annual_income: 25000,
      family_size: 8,
      occupation: 'Laborer',
      skills: 'Construction, Masonry',
      bank_account: '3456789012345678',
      ifsc_code: 'SBIN0000003',
      eligibility_score: 95,
      is_verified: 0,
      created_at: '2024-01-17T09:45:00Z'
    },
    {
      id: 4,
      name: 'Sunita Devi',
      age: 29,
      gender: 'Female',
      state: 'Rajasthan',
      district: 'Jaipur',
      caste_category: 'SC',
      aadhar_number: '456789012345',
      phone: '9876543213',
      email: 'sunita.devi@email.com',
      education_level: 'No formal education',
      annual_income: 20000,
      family_size: 7,
      occupation: 'Domestic Worker',
      skills: 'Cooking, Cleaning',
      bank_account: '4567890123456789',
      ifsc_code: 'SBIN0000004',
      eligibility_score: 100,
      is_verified: 1,
      created_at: '2024-01-18T14:20:00Z'
    },
    {
      id: 5,
      name: 'Vikram Yadav',
      age: 35,
      gender: 'Male',
      state: 'Maharashtra',
      district: 'Mumbai',
      caste_category: 'SC',
      aadhar_number: '567890123456',
      phone: '9876543214',
      email: 'vikram.yadav@email.com',
      education_level: 'Graduate',
      annual_income: 80000,
      family_size: 4,
      occupation: 'Driver',
      skills: 'Driving, Vehicle Maintenance',
      bank_account: '5678901234567890',
      ifsc_code: 'SBIN0000005',
      eligibility_score: 60,
      is_verified: 1,
      created_at: '2024-01-19T16:10:00Z'
    }
  ],
  projects: [
    {
      id: 1,
      beneficiary_id: 1,
      title: 'Organic Vegetable Farming',
      description: 'Establishing organic vegetable farming with modern irrigation techniques to increase crop yield and income',
      category: 'Income Generation',
      project_type: 'Agriculture',
      requested_amount: 50000,
      approved_amount: 45000,
      status: 'in_progress',
      priority_score: 85,
      completion_percentage: 60,
      submission_date: '2024-01-20T10:00:00Z',
      beneficiary_name: 'Rajesh Kumar',
      state: 'Uttar Pradesh',
      district: 'Lucknow'
    },
    {
      id: 2,
      beneficiary_id: 2,
      title: 'Tailoring Business Setup',
      description: 'Setting up a small tailoring business with modern equipment and training',
      category: 'Income Generation',
      project_type: 'Small Business',
      requested_amount: 30000,
      approved_amount: 30000,
      status: 'completed',
      priority_score: 90,
      completion_percentage: 100,
      submission_date: '2024-01-21T11:30:00Z',
      beneficiary_name: 'Priya Sharma',
      state: 'Bihar',
      district: 'Patna'
    },
    {
      id: 3,
      beneficiary_id: 3,
      title: 'Construction Skills Training',
      description: 'Advanced construction and masonry skills training program for better employment opportunities',
      category: 'Skill Development',
      project_type: 'Training',
      requested_amount: 25000,
      approved_amount: 20000,
      status: 'approved',
      priority_score: 95,
      completion_percentage: 0,
      submission_date: '2024-01-22T09:15:00Z',
      beneficiary_name: 'Amit Singh',
      state: 'Madhya Pradesh',
      district: 'Bhopal'
    },
    {
      id: 4,
      beneficiary_id: 4,
      title: 'Community Kitchen Setup',
      description: 'Establishing a community kitchen for local events and catering services',
      category: 'Income Generation',
      project_type: 'Food Service',
      requested_amount: 40000,
      approved_amount: 35000,
      status: 'in_progress',
      priority_score: 100,
      completion_percentage: 30,
      submission_date: '2024-01-23T13:45:00Z',
      beneficiary_name: 'Sunita Devi',
      state: 'Rajasthan',
      district: 'Jaipur'
    },
    {
      id: 5,
      beneficiary_id: 5,
      title: 'Vehicle Maintenance Workshop',
      description: 'Setting up a small vehicle maintenance and repair workshop',
      category: 'Income Generation',
      project_type: 'Automotive',
      requested_amount: 60000,
      approved_amount: 50000,
      status: 'submitted',
      priority_score: 60,
      completion_percentage: 0,
      submission_date: '2024-01-24T15:20:00Z',
      beneficiary_name: 'Vikram Yadav',
      state: 'Maharashtra',
      district: 'Mumbai'
    }
  ],
  dashboardStats: {
    totalBeneficiaries: 5,
    verifiedBeneficiaries: 4,
    avgEligibilityScore: 86,
    totalProjects: 5,
    activeProjects: 2,
    completedProjects: 1,
    totalFundingApproved: 190000,
    topStates: [
      { state: 'Uttar Pradesh', count: 1 },
      { state: 'Bihar', count: 1 },
      { state: 'Madhya Pradesh', count: 1 },
      { state: 'Rajasthan', count: 1 },
      { state: 'Maharashtra', count: 1 }
    ],
    projectsByCategory: [
      { category: 'Income Generation', count: 4 },
      { category: 'Skill Development', count: 1 }
    ]
  }
};
